version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      aksel:
        applies-to: version-updates
        patterns:
          - "@navikt/aksel*"
          - "@navikt/ds*"
      react-router:
        applies-to: version-updates
        patterns:
          - "@react-router*"
          - "react-router*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
